---
- name: Download core Mediawiki
  git:
    dest: "{{ mediawiki_path }}"
    version: "{{ mediawiki_version }}"
    force: true
    repo: https://github.com/wikimedia/mediawiki.git
  notify:
    - composer update mediawiki
    - maintenance update mediawiki

- name: Download mediawiki extensions
  git:
    dest: "{{ mediawiki_path }}/extensions/{{ item.name }}"
    version: "{{ item.version | default(mediawiki_version) }}"
    force: true
    repo: "{{ item.git | default('https://github.com/wikimedia/mediawiki-extensions-' + item.name + '.git') }}"
  loop: "{{ mediawiki_extensions }}"
  notify:
    - composer update mediawiki
    - maintenance update mediawiki

- name: Download mediawiki skins
  git:
    dest: "{{ mediawiki_path }}/skins/{{ item.name }}"
    version: "{{ item.version | default(mediawiki_version) }}"
    force: true
    repo: "{{ item.git | default('https://github.com/wikimedia/mediawiki-skins-' + item.name + '.git') }}"
  loop: "{{ mediawiki_skins }}"
  notify:
    - composer update mediawiki
    - maintenance update mediawiki


- name: Install mediawiki (mysql/postgresql)
  command:
    argv:
      - php
      - "{{ mediawiki_path }}/maintenance/install.php"
      - --dbtype={{ mediawiki_database.type }}
      - --dbname={{ mediawiki_database.name }}
      - --dbuser={{ mediawiki_database.user }}
      - --dbpass={{ mediawiki_database.password }}
      - --dbserver={{ mediawiki_database.server | default('localhost') }}
      - --pass={{ mediawiki_admin_pass }}
      - "{{ mediawiki_wiki_name }}"
      - "{{ mediawiki_admin_user }}"
  args:
    creates: "{{ mediawiki_path }}/LocalSettings.php"

- name: Configure mediawiki
  template:
    src: LocalSettings.php.j2
    dest: "{{ mediawiki_path }}/LocalSettings.php"
  notify:
    - maintenance update mediawiki
