---
- name: composer update mediawiki
  composer:
    command: install
    working_dir: "{{ mediawiki_path }}"

- name: maintenance update mediawiki
  command: php {{ mediawiki_path }}/maintenance/update.php --quick
