---
- hosts: all
  become: true

  vars:
    php_version: '7.3'
    php_packages_extra:
      - php-postgresql
      - php-intl
      - php-pecl-zip

    mediawiki_database:
      type: postgres
      user: mediawiki
      name: mediawiki
      password: mediawiki

    mediawiki_admin_user: mediawiki
    mediawiki_admin_pass: mediawiki

    postgresql_databases:
      - name: "{{ mediawiki_database.name }}"
    postgresql_users:
      - name: "{{ mediawiki_database.user }}"
        password: "{{ mediawiki_database.password }}"
        priv: "{{ mediawiki_database.name }}.*:ALL"

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.git
    - role: geerlingguy.postgresql
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: daveol.mediawiki
