---
- hosts: all
  become: true

  vars:
    php_version: '7.3'
    php_packages_extra:
      - php-intl
      - php-pecl-zip

    mediawiki_database:
      type: sqlite

    mediawiki_admin_user: mediawiki
    mediawiki_admin_pass: mediawiki

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.git
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: daveol.mediawiki
